# ---------------------------------------------------------------------------------------------
# This docker compose file bring up the Docker containers for run Hyperledger Fabric Network
# ---------------------------------------------------------------------------------------------
version: '2'

networks:
  network:

services:

  mysql.ca.govt:
    container_name: mysql.ca.govt
    extends:
      file: base.yaml
      service: mysql-base
    volumes:
      - ./Backup/Govt/CA:/var/lib/mysql
    networks:
      - network

  mysql.ca.builder:
    container_name: mysql.ca.builder
    extends:
      file: base.yaml
      service: mysql-base
    volumes:
      - ./Backup/Builder/CA:/var/lib/mysql
    networks:
      - network

  mysql.ca.user:
    container_name: mysql.ca.user
    extends:
      file: base.yaml
      service: mysql-base
    volumes:
      - ./Backup/User/CA:/var/lib/mysql
    networks:
      - network

  ca.govt.jeabc.com:
    container_name: ca.govt.jeabc.com
    image: hyperledger/fabric-ca:1.1.0
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-govt
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.govt.jeabc.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/992a6fbe4acb0a5cd312e6b6555fe0f8773678077bef5e90211533e77e6478ac_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.govt.jeabc.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/992a6fbe4acb0a5cd312e6b6555fe0f8773678077bef5e90211533e77e6478ac_sk
      - FABRIC_CA_SERVER_DB_TYPE=mysql
      - FABRIC_CA_SERVER_DB_DATASOURCE=root:${MYSQL_PASSWORD}@tcp(mysql.ca.govt:3306)/fabric_ca?parseTime=true
    ports:
      - "15111:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.govt.jeabc.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/992a6fbe4acb0a5cd312e6b6555fe0f8773678077bef5e90211533e77e6478ac_sk'
    volumes:
      - ./channel/crypto-config/peerOrganizations/govt.jeabc.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - network
    depends_on:
      - mysql.ca.govt

  ca.builder.jeabc.com:
    container_name: ca.builder.jeabc.com
    image: hyperledger/fabric-ca:1.1.0
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-builder
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.builder.jeabc.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/c47aaed92f4b6d51189a7d29d7c251d9ded541367ce20d99431cf19f4e7b3eef_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.builder.jeabc.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/c47aaed92f4b6d51189a7d29d7c251d9ded541367ce20d99431cf19f4e7b3eef_sk
      - FABRIC_CA_SERVER_DB_TYPE=mysql
      - FABRIC_CA_SERVER_DB_DATASOURCE=root:${MYSQL_PASSWORD}@tcp(mysql.ca.builder:3306)/fabric_ca?parseTime=true
    ports:
      - "15112:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.builder.jeabc.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/c47aaed92f4b6d51189a7d29d7c251d9ded541367ce20d99431cf19f4e7b3eef_sk'
    volumes:
      - ./channel/crypto-config/peerOrganizations/builder.jeabc.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - network
    depends_on:
      - mysql.ca.builder

  ca.user.jeabc.com:
    container_name: ca.user.jeabc.com
    image: hyperledger/fabric-ca:1.1.0
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-user
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.user.jeabc.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/25759641683807f013f8589c857e70b7261b5089518a8551d6e2a2ad02553b52_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.user.jeabc.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/25759641683807f013f8589c857e70b7261b5089518a8551d6e2a2ad02553b52_sk
      - FABRIC_CA_SERVER_DB_TYPE=mysql
      - FABRIC_CA_SERVER_DB_DATASOURCE=root:${MYSQL_PASSWORD}@tcp(mysql.ca.user:3306)/fabric_ca?parseTime=true
    ports:
      - "15113:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.user.jeabc.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/25759641683807f013f8589c857e70b7261b5089518a8551d6e2a2ad02553b52_sk'
    volumes:
      - ./channel/crypto-config/peerOrganizations/user.jeabc.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - network
    depends_on:
      - mysql.ca.user

  zookeeper0:
    container_name: zookeeper0.jeabc.com
    extends:
      file: base.yaml
      service: zookeeper-base
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    volumes:
      - ./Backup/Zookeeper/zk0/data:/data
      - ./Backup/Zookeeper/zk0/datalog:/datalog
    networks:
      - network

  zookeeper1:
    container_name: zookeeper1.jeabc.com
    extends:
      file: base.yaml
      service: zookeeper-base
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    volumes:
      - ./Backup/Zookeeper/zk1/data:/data
      - ./Backup/Zookeeper/zk1/datalog:/datalog
    networks:
      - network

  zookeeper2:
    container_name: zookeeper2.jeabc.com
    extends:
      file: base.yaml
      service: zookeeper-base
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    volumes:
      - ./Backup/Zookeeper/zk2/data:/data
      - ./Backup/Zookeeper/zk2/datalog:/datalog
    networks:
      - network

  kafka0:
    container_name: kafka0.jeabc.com
    extends:
      file: base.yaml
      service: kafka-base
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    volumes:
      - ./Backup/Kafka/kafka0:/tmp/kafka-logs
    networks:
      - network
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2

  kafka1:
    container_name: kafka1.jeabc.com
    extends:
      file: base.yaml
      service: kafka-base
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    volumes:
      - ./Backup/Kafka/kafka1:/tmp/kafka-logs
    networks:
      - network
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2

  kafka2:
    container_name: kafka2.jeabc.com
    extends:
      file: base.yaml
      service: kafka-base
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    volumes:
      - ./Backup/Kafka/kafka2:/tmp/kafka-logs
    networks:
      - network
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2

  kafka3:
    container_name: kafka3.jeabc.com
    extends:
      file: base.yaml
      service: kafka-base
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    volumes:
      - ./Backup/Kafka/kafka3:/tmp/kafka-logs
    networks:
      - network
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2

  orderer1.jeabc.com:
    container_name: orderer1.jeabc.com
    extends:
      file: base.yaml
      service: orderer-base
    ports:
      - 15101:7050
    volumes:
      - ./channel/crypto-config/ordererOrganizations/jeabc.com/orderers/orderer1.jeabc.com/:/etc/hyperledger/msp/orderer
    networks:
      - network
    depends_on:
      - kafka0
      - kafka1
      - kafka2
      - kafka3

  orderer2.jeabc.com:
    container_name: orderer2.jeabc.com
    extends:
      file: base.yaml
      service: orderer-base
    ports:
      - 15102:7050
    volumes:
      - ./channel/crypto-config/ordererOrganizations/jeabc.com/orderers/orderer2.jeabc.com/:/etc/hyperledger/msp/orderer
    networks:
      - network
    depends_on:
      - kafka0
      - kafka1
      - kafka2
      - kafka3

  orderer3.jeabc.com:
    container_name: orderer3.jeabc.com
    extends:
      file: base.yaml
      service: orderer-base
    ports:
      - 15103:7050
    volumes:
      - ./channel/crypto-config/ordererOrganizations/jeabc.com/orderers/orderer3.jeabc.com/:/etc/hyperledger/msp/orderer
    networks:
      - network
    depends_on:
      - kafka0
      - kafka1
      - kafka2
      - kafka3

  couchdb.peer0.govt.jeabc.com:
    container_name: couchdb.peer0.govt.jeabc.com
    extends:
      file: base.yaml
      service: couch-base
    volumes:
      - ./Backup/Govt/CouchDb/peer0:/opt/couchdb/data
    networks:
      - network

  peer0.govt.jeabc.com:
    container_name: peer0.govt.jeabc.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.govt.jeabc.com
      - CORE_PEER_LOCALMSPID=GovtMSP
      - CORE_PEER_ADDRESS=peer0.govt.jeabc.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.govt.jeabc.com:7051
      - CORE_PEER_LISTENADDRESS=peer0.govt.jeabc.com:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.govt.jeabc.com:7051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.govt.jeabc.com:5984
    ports:
      - 15121:7051
      - 15123:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./channel/crypto-config/peerOrganizations/govt.jeabc.com/peers/peer0.govt.jeabc.com/:/etc/hyperledger/msp/peer
      - ./Backup/Govt/Peer/peer0:/var/hyperledger/production
    depends_on:
      - orderer1.jeabc.com
      - orderer2.jeabc.com
      - orderer3.jeabc.com
      - couchdb.peer0.govt.jeabc.com
    networks:
      - network

  couchdb.peer0.builder.jeabc.com:
    container_name: couchdb.peer0.builder.jeabc.com
    extends:
      file: base.yaml
      service: couch-base
    volumes:
      - ./Backup/Builder/CouchDb/peer0:/opt/couchdb/data
    networks:
      - network

  peer0.builder.jeabc.com:
    container_name: peer0.builder.jeabc.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.builder.jeabc.com
      - CORE_PEER_LOCALMSPID=BuilderMSP
      - CORE_PEER_ADDRESS=peer0.builder.jeabc.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.builder.jeabc.com:7051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.builder.jeabc.com:5984
      - CORE_PEER_LISTENADDRESS=peer0.builder.jeabc.com:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.builder.jeabc.com:7051
    ports:
      - 15133:7051
      - 15135:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./channel/crypto-config/peerOrganizations/builder.jeabc.com/peers/peer0.builder.jeabc.com/:/etc/hyperledger/msp/peer
      - ./Backup/Builder/Peer/peer0:/var/hyperledger/production
    depends_on:
      - orderer1.jeabc.com
      - orderer2.jeabc.com
      - orderer3.jeabc.com
      - couchdb.peer0.builder.jeabc.com
    networks:
      - network

  couchdb.peer0.user.jeabc.com:
    container_name: couchdb.peer0.user.jeabc.com
    extends:
      file: base.yaml
      service: couch-base
    volumes:
      - ./Backup/User/CouchDb/peer0:/opt/couchdb/data
    networks:
      - network

  peer0.user.jeabc.com:
    container_name: peer0.user.jeabc.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.user.jeabc.com
      - CORE_PEER_LOCALMSPID=UserMSP
      - CORE_PEER_ADDRESS=peer0.user.jeabc.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.user.jeabc.com:7051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.user.jeabc.com:5984
      - CORE_PEER_LISTENADDRESS=peer0.user.jeabc.com:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.user.jeabc.com:7051
    ports:
      - 15145:7051
      - 15147:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./channel/crypto-config/peerOrganizations/user.jeabc.com/peers/peer0.user.jeabc.com/:/etc/hyperledger/msp/peer
      - ./Backup/User/Peer/peer0:/var/hyperledger/production
    depends_on:
      - orderer1.jeabc.com
      - orderer2.jeabc.com
      - orderer3.jeabc.com
      - couchdb.peer0.user.jeabc.com
    networks:
      - network
